### PR TITLE
Reference: Changed description for data-transition

### PR DESCRIPTION
**Pull request by agcolom**
Fixes gh-381

### CODE REVIEW

**Comment by agcolom** [comment]
@arschmitz @jaspermdegroot

**Comment by jaspermdegroot** [comment]
:+1: 

Ps. I kinda forgot how we handled branches for different API docs versions so I am not sure if this needs to be cherry picked into the 1-5 branch. I suppose we can do a rebase of that branch against master to make sure fixes like this one end up in the 1-5 branch.

**Comment by agcolom** [comment]
@jaspermdegroot Thanks. Yes I don't know either what is the status of 1-5 branch. Maybe @gabrielschulhof would know?

**Comment by agcolom** [comment]
Notes from the mobile meeting today: we will need to cherry-pick. I will land in master and liaise with @arschmitz for the cherry-picking.

**Pull request closed without merging**
