### PR TITLE
Navigation: Clarify the circumstances of and data associated with pagebeforechange

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes gh-355

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
@agcolom I've removed the "already".

**Comment by agcolom** [comment]
@gabrielschulhof Thank you. LGTM

**Comment by arthurvr** [comment]
Is this PR ready to get merged?

**Comment by arschmitz** [comment]
:+1:

**Pull request closed without merging**
