### PR TITLE
All: Remove deprecated entries

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes gh-395

### CODE REVIEW

**Comment by apsdehal** [comment]
There are many more to be removed yet like dialog etc.

**Comment by gabrielschulhof** [comment]
@apsdehal yeah, I'm gonna add more.

**Comment by apsdehal** [comment]
@gabrielschulhof Take care of some deprecation changes I have made in classes PR.

**Comment by arschmitz** [comment]
👍

**Pull request closed without merging**
